name: Laravel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite
          coverage: none

      # Composer Update
      - name: Update composer
        run: composer update

      # Install Composer dependencies
      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install Node dependencies
      - name: Install NPM Dependencies
        run: npm install

      # Build frontend assets (Vite / Mix)
      - name: Build Assets
        run: npm run build

      # Optimize Laravel
      #- name: Optimize Laravel
      #  run: |
      #    php artisan config:cache
      #    php artisan route:cache
      #    php artisan view:cache

      #    php artisan key:generate

      # Upload build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-build
          path: |
            vendor
            public/build
            bootstrap/cache
            
      - name: Deploy to prod branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Fetch prod in case it exists
          git fetch origin prod || true

          # Backup prod
          if git show-ref --verify --quiet refs/heads/prod; then
            echo "Branch prod exists"
            TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
            git checkout prod
            git checkout -b prod-backup-$TIMESTAMP
            git push origin prod-backup-$TIMESTAMP
          else
              echo "Branch prod does not exist"
          fi

          # Return to main to copy files
          git checkout main

          # Prepare a temporary directory for prod branch
          mkdir ../prod-temp
          cp -r app bootstrap config database public resources routes artisan composer.json composer.lock vendor ../prod-temp/

          # Switch to prod branch
          git checkout --orphan prod
          git rm -rf .

          # Copy files from temp
          cp -r ../prod-temp/* ./

          git add .
          git commit -m "Deploy build from main"
          git push origin prod --force
